name: FakePlayersOnline
main: fromgate.fakeplayersonline.FakePlayersOnline
version: 0.1.0
author: fromgate
softdepend: [Citizens,ProtocolLib]
commands:
   fpo:
      description: FakePlayersOnline commands
      usage: |
           /fpo help